namespace TrollStrategy.Content
{
    // Values are serialized by index: append new kinds, never reorder.
    // Enum order is also the order in which haulers pick goods and storages fill slots.
    public enum ResourceKind
    {
        IronOre,
        IronIngot,
        Wheat,
        AnimalHide,
        Leather,
        Logs,
        Planks,
        IronSword,
        IronArmor,
        WoodenShield,
        VioletCrystal,
        EnchantedSword,
        Coal,
        GoldNugget,
        Straw,
        GoldenWheat,
        Meat,
        Milk,
        Scrap,
        Feast,
        BattleAxe,
        // Vitaria kit 2026-10-02: mine by-products, smeltery metals, wool and cloth
        Stone,
        CopperOre,
        CopperIngot,
        GoldOre,
        GoldIngot,
        Steel,
        Wool,
        Cloth,
        // the arena's trophies, before only starting gear, and the kit's new gear
        RustySword,
        PatchedArmor,
        SteelSword,
        Spear,
        Bow,
        WarHammer,
        LeatherArmor,
        Chainmail,
        SteelArmor,
        Helmet,
        IronShield,
        // the enchanter's work on each of them (the iron sword's is EnchantedSword)
        EnchantedRustySword,
        EnchantedSteelSword,
        EnchantedBattleAxe,
        EnchantedSpear,
        EnchantedBow,
        EnchantedWarHammer,
        EnchantedPatchedArmor,
        EnchantedLeatherArmor,
        EnchantedIronArmor,
        EnchantedChainmail,
        EnchantedSteelArmor,
        EnchantedHelmet,
        EnchantedWoodenShield,
        EnchantedIronShield
    }
}
