using System;
using System.Collections.Generic;
using UnityEngine;

namespace TrollStrategy.Presentation.Audio
{
    /// <summary>
    /// Feedback sounds. Each cue has takes in Assets/Game/Audio/Resources/Sfx: <c>name.wav</c>, <c>name_2.wav</c>, …,
    /// generated by assets/audio/sfx/build_sfx.py in F major pentatonic, the key of the music.
    /// </summary>
    public enum Sfx
    {
        UiHover, UiClick, UiBack, UiDenied, Equip, Unequip, Coins, Pause, Unpause,
        Select, Land, Build, Step, Spawn, Upgrade, Demolish,
        Swing, Throw, Hit, HitHeavy, Block, Death, BattleStart, Victory, Defeat,
    }

    /// <summary>
    /// Restrained 2D feedback. Plays a different take than last time, keeps tuned cues in key, and limits
    /// repeated cues and overlapping voices so busy scenes stay quiet.
    /// </summary>
    public sealed class GameAudio : MonoBehaviour
    {
        private const int Voices = 8;
        private const int MaxSameCue = 2;
        private const int MaxTakes = 12;
        // semitones of the major pentatonic above a tuned cue's own note
        private static readonly int[] Pentatonic = { 0, 2, 4, 7, 9 };

        private static GameAudio s_instance;
        private static readonly Dictionary<Sfx, string> Files = new()
        {
            [Sfx.UiHover] = "ui_hover", [Sfx.UiClick] = "ui_click", [Sfx.UiBack] = "ui_back",
            [Sfx.UiDenied] = "ui_denied", [Sfx.Equip] = "equip", [Sfx.Unequip] = "unequip",
            [Sfx.Coins] = "coins", [Sfx.Pause] = "pause", [Sfx.Unpause] = "unpause",
            [Sfx.Select] = "select", [Sfx.Land] = "land", [Sfx.Build] = "build", [Sfx.Step] = "step",
            [Sfx.Spawn] = "spawn", [Sfx.Upgrade] = "upgrade", [Sfx.Demolish] = "demolish",
            [Sfx.Swing] = "swing", [Sfx.Throw] = "throw", [Sfx.Hit] = "hit", [Sfx.HitHeavy] = "hit_heavy",
            [Sfx.Block] = "block", [Sfx.Death] = "death", [Sfx.BattleStart] = "battle_start",
            [Sfx.Victory] = "victory", [Sfx.Defeat] = "defeat",
        };
        // Every take is mastered to the same short-term loudness, so these gains are the whole mix: results
        // loudest, then colony actions and hits, then UI, with steps and hover a whisper over the music.
        private static readonly Dictionary<Sfx, float> Levels = new()
        {
            [Sfx.UiHover] = .07f, [Sfx.UiClick] = .16f, [Sfx.UiBack] = .13f, [Sfx.UiDenied] = .16f,
            [Sfx.Equip] = .16f, [Sfx.Unequip] = .14f, [Sfx.Pause] = .16f, [Sfx.Unpause] = .16f,
            [Sfx.Select] = .14f, [Sfx.Step] = .05f, [Sfx.Coins] = .22f,
            [Sfx.Land] = .22f, [Sfx.Build] = .25f, [Sfx.Spawn] = .25f,
            [Sfx.Upgrade] = .32f, [Sfx.Demolish] = .22f,
            [Sfx.Swing] = .18f, [Sfx.Throw] = .16f, [Sfx.Hit] = .22f,
            [Sfx.HitHeavy] = .28f, [Sfx.Block] = .2f, [Sfx.Death] = .25f,
            [Sfx.BattleStart] = .5f, [Sfx.Victory] = .63f, [Sfx.Defeat] = .45f,
        };
        // kalimba, marimba and chimes: a random pitch would pull them out of key
        private static readonly HashSet<Sfx> Tuned = new()
        {
            Sfx.Select, Sfx.Pause, Sfx.Unpause, Sfx.Land, Sfx.Build, Sfx.Spawn, Sfx.Upgrade,
            Sfx.Death, Sfx.BattleStart, Sfx.Victory, Sfx.Defeat,
        };

        private readonly Dictionary<Sfx, AudioClip[]> _takes = new();
        private readonly Dictionary<Sfx, int> _lastTake = new();
        private readonly Dictionary<Sfx, float> _lastPlayed = new();
        private AudioSource[] _voices = Array.Empty<AudioSource>();
        private Sfx[] _voiceCues = Array.Empty<Sfx>();
        private int _next;

        /// <summary>Overall effects volume 0..1.</summary>
        public static float Volume { get; set; } = 1f;

        /// <summary>
        /// Plays a take of the cue. Tuned cues ignore <paramref name="pitchJitter"/>; move them with
        /// <see cref="Step"/> or <see cref="Semitones"/> so they stay in key.
        /// </summary>
        public static void Play(Sfx sfx, float volume = 1f, float pitch = 1f, float pitchJitter = .025f)
        {
            var audio = Instance;
            if (audio != null) audio.PlayInternal(sfx, volume, pitch, pitchJitter);
        }

        /// <summary>Pitch that moves a tuned cue <paramref name="steps"/> notes up (or down) the pentatonic scale.</summary>
        public static float Step(int steps)
        {
            int octave = Mathf.FloorToInt(steps / (float)Pentatonic.Length);
            int degree = steps - octave * Pentatonic.Length;
            return Semitones(octave * 12 + Pentatonic[degree]);
        }

        public static float Semitones(int semitones) => Mathf.Pow(2f, semitones / 12f);

        public static bool IsTuned(Sfx sfx) => Tuned.Contains(sfx);

        /// <summary>
        /// Which of <paramref name="count"/> takes to play for <paramref name="roll"/> in 0..1: never the
        /// <paramref name="last"/> one again when there is a choice.
        /// </summary>
        public static int PickTake(int count, int last, float roll)
        {
            if (count <= 1) return 0;
            bool avoid = last >= 0 && last < count;
            int options = avoid ? count - 1 : count;
            int pick = Mathf.Clamp((int)(roll * options), 0, options - 1);
            return avoid && pick >= last ? pick + 1 : pick;
        }

        /// <summary>The cue's takes in order: <c>name</c>, then <c>name_2</c>, <c>name_3</c>… until one is missing.</summary>
        public static AudioClip[] LoadTakes(Sfx sfx)
        {
            var takes = new List<AudioClip>();
            if (!Files.TryGetValue(sfx, out var file)) return takes.ToArray();
            var first = Resources.Load<AudioClip>("Sfx/" + file);
            if (first == null) return takes.ToArray();
            takes.Add(first);
            for (int i = 2; i <= MaxTakes; i++)
            {
                var take = Resources.Load<AudioClip>($"Sfx/{file}_{i}");
                if (take == null) break;
                takes.Add(take);
            }
            return takes.ToArray();
        }

        private static GameAudio Instance
        {
            get
            {
                if (s_instance != null) return s_instance;
                if (!UnityEngine.Application.isPlaying) return null;
                var go = new GameObject("GameAudio");
                DontDestroyOnLoad(go);
                s_instance = go.AddComponent<GameAudio>();
                return s_instance;
            }
        }

        private void Awake()
        {
            _voices = new AudioSource[Voices];
            _voiceCues = new Sfx[Voices];
            for (int i = 0; i < Voices; i++)
            {
                var voice = gameObject.AddComponent<AudioSource>();
                voice.playOnAwake = false;
                voice.spatialBlend = 0f;
                voice.priority = 96;
                _voices[i] = voice;
            }
        }

        private void OnDestroy()
        {
            if (s_instance == this) s_instance = null;
        }

        private void PlayInternal(Sfx sfx, float volume, float pitch, float pitchJitter)
        {
            float gain = Mathf.Clamp01(volume * Level(sfx) * Volume);
            if (gain <= 0f) return;
            var takes = Takes(sfx);
            if (takes.Length == 0) return;
            // Space recurring activity independently of render frames and simulation speed.
            float now = Time.unscaledTime;
            if (_lastPlayed.TryGetValue(sfx, out float last) && now - last < RepeatInterval(sfx)) return;

            int playing = 0;
            for (int i = 0; i < _voices.Length; i++)
                if (_voices[i].isPlaying && _voiceCues[i] == sfx) playing++;
            int limit = sfx == Sfx.Step || sfx == Sfx.Coins ? 1 : MaxSameCue;
            if (playing >= limit) return;

            int voice = FreeVoice();
            if (voice < 0) return;
            int take = PickTake(takes.Length, _lastTake.TryGetValue(sfx, out int lastTake) ? lastTake : -1,
                UnityEngine.Random.value);
            _lastTake[sfx] = take;
            _lastPlayed[sfx] = now;
            _voiceCues[voice] = sfx;
            var source = _voices[voice];
            source.clip = takes[take];
            source.volume = gain;
            float jitter = IsTuned(sfx) ? 0f : Mathf.Clamp(pitchJitter, 0f, .04f);
            source.pitch = Mathf.Clamp(pitch * (1f + UnityEngine.Random.Range(-jitter, jitter)), .5f, 2f);
            source.Play();
        }

        private int FreeVoice()
        {
            for (int i = 0; i < _voices.Length; i++)
            {
                int index = (_next + i) % _voices.Length;
                if (_voices[index].isPlaying) continue;
                _next = (index + 1) % _voices.Length;
                return index;
            }
            // Dropping excess feedback avoids both a louder pile-up and a hard cut in a playing clip.
            return -1;
        }

        private AudioClip[] Takes(Sfx sfx)
        {
            if (_takes.TryGetValue(sfx, out var takes)) return takes;
            takes = LoadTakes(sfx);
            _takes[sfx] = takes;
            return takes;
        }

        private static float RepeatInterval(Sfx sfx) => sfx switch
        {
            Sfx.Step => .18f,
            Sfx.Coins => .45f,
            Sfx.UiDenied => .25f,
            Sfx.Death => .2f,
            Sfx.BattleStart or Sfx.Victory or Sfx.Defeat => .75f,
            _ => .1f,
        };

        private static float Level(Sfx sfx) => Levels.TryGetValue(sfx, out float level) ? level : .2f;
    }
}
